### ISSUE TITLE
Task with output string is not correcly converted

### ISSUE THREAD

**Issue by nesies** [camunda-community-hub/camunda-7-to-8-migration#976] opened 2024-08-22 10:31 UTC
### Describe the bug

i have a Task which only set a variable _var1_ to value _1_
 
workaround, set the value in a ${ } block:
```
          <camunda:outputParameter name="var1">${ "1" }</camunda:outputParameter>
```
### Steps to reproduce

1. create a bpmn with a task which set a output string
```
 <bpmn:task id="Activity_set_var1" name="set var1">
      <bpmn:extensionElements>
        <camunda:inputOutput>
          <camunda:outputParameter name="var1">1</camunda:outputParameter>
        </camunda:inputOutput>
      </bpmn:extensionElements>
```

2. convert it to camunda8
```
java -Dfile.encoding=UTF-8 -jar backend-diagram-converter-cli-0.9.0.jar
```
```
    <bpmn:task completionQuantity="1" id="Activity_set_var1" isForCompensation="false" name="set var1" startQuantity="1">
      <bpmn:extensionElements>
        <conversion:message severity="REVIEW">Element 'outputParameter' was transformed. Parameter 'var1': Please review transformed expression: '1' -&gt; '1'.</conversion:message>
        <zeebe:ioMapping>
          <zeebe:output source="1" target="var1"/>
        </zeebe:ioMapping>
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_1yiy9op</bpmn:incoming>
      <bpmn:outgoing>Flow_1n0rl0c</bpmn:outgoing>
    </bpmn:task>
```

3. deploy it
```
      debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Command \'CREATE\' rejected with code \'INVALID_ARGUMENT\': Expected to deploy new resources, but encountered the following errors:\n\'converted-c8-e.bpmn\': - Element: Activity_set_var1 > extensionElements > ioMapping > output\n    - ERROR: Expected expression but found static value \'1\'. An expression must start with \'=\' (e.g. \'=1\').\n", grpc_status:3, created_time:"2024-08-22T12:28:23.053665545+02:00"}"
```

### Expected Behaviour

i think a _&quot;_ is missing somewhere:

```
          <zeebe:output source="=&quot;1&quot;" target="var1"/>
```

### Library version

0.9.0

### Camunda Platform 7 version

7.21

### Camunda Platform 8 version

8.5

**Comment by jonathanlukas** [comment] 2024-12-02 13:08
duplicate of #978

**Closed by jonathanlukas** 2024-12-02 13:08 UTC
Labels: duplicate
