### ISSUE TITLE
Umlauts/encoding in the web version of the diagram converter

### ISSUE THREAD

**Issue by hkupitz** [camunda-community-hub/camunda-7-to-8-migration#438] opened 2023-10-02 13:34 UTC
### Describe the bug

When uploading a BPMN diagram with umlauts in the XML, the encoding is not set correctly. As a result the output contains question marks.
![image](https://github.com/camunda-community-hub/camunda-7-to-8-migration/assets/27265759/74a1a6c3-c101-4bba-b5ba-58216c2f68ae)
![image](https://github.com/camunda-community-hub/camunda-7-to-8-migration/assets/27265759/b3d9d8c8-1ef7-488c-b187-68b62bf32662)

### Steps to reproduce

1. Create a BPMN diagram with umlauts in the XML (e.g., as part of a label, documentation etc.).
2. Upload the BPMN file to the [diagram converter](https://diagram-converter.consulting-sandbox.camunda.cloud/).
3. Click on "Convert and download".
4. Open the result in the Camunda Desktop Modeler.

### Expected Behaviour

The converted diagrams should be processed correctly, with no question marks replacing the umlauts.

### Library version

0.6.2

**Comment by jonathanlukas** [comment] 2023-10-17 11:47
The cause for this issue is the `LANG` env variable not being defined properly.

**Comment by jonathanlukas** [comment] 2023-10-17 12:40
@hkupitz is fixed on live system, a patch will be made to build the image correctly by default

**Closed** 2023-10-23 09:23 UTC
Labels: bug, component:diagram-converter
